import Foundation
import SwiftData

/// Drives the per-meeting Recap popup that appears ~8 sec after a meeting
/// stops (2026-04-29). The popup shows the just-finished conversation's
/// title + emoji + overview, action items extracted by `TaskExtractor`, and
/// memories extracted by `MemoryExtractor`. Click "Open in Library" → main
/// window scrolls to the conversation. "Copy" → shareable text to clipboard.
///
/// All data is read by id at show time — we don't snapshot, so any in-flight
/// extraction that finishes between schedule + show will be reflected.
@MainActor
final class MeetingRecapState: ObservableObject {
    static let shared = MeetingRecapState()

    /// Snapshot of what's displayed. Re-fetched right before show so late
    /// extractions land in the popup. `actionItems` is var so the in-popup
    /// checkbox-toggle path (`toggleTask`) can flip a row's completed flag
    /// without invalidating the whole payload.
    /// Structured fields (`participants` / `decisions` / `nextSteps`) come
    /// from `Conversation.{participantsJSON, decisionsJSON, nextStepsJSON}`
    /// — generated by StructuredGenerator. Recap UI was rendering only
    /// ABOUT before, leaving the rest invisible despite being saved
    /// (2026-05-01 user report: "созвон с тремя людьми / о чём договорились
    /// — почему не показывает?").
    struct Payload {
        let conversationId: UUID
        let emoji: String?
        let title: String
        let overview: String
        let durationSec: Double
        let language: String?
        let calendarEventTitle: String?
        let participants: [String]
        let decisions: [String]
        let nextSteps: [String]
        var actionItems: [ActionItem]
        let memories: [MemoryRow]
        let transcript: String
    }

    struct ActionItem: Identifiable {
        let id: UUID
        let description: String
        let assignee: String?
        var completed: Bool
    }

    struct MemoryRow: Identifiable {
        let id: UUID
        let kind: String?
        let subject: String?
        let characterization: String?
        let content: String
    }

    @Published private(set) var payload: Payload?
    @Published private(set) var isVisible: Bool = false

    private init() {}

    /// Called by AppDelegate.fireMeetingRecap once the conversation is closed
    /// and structured-gen + extractors have had time to populate.
    func present(_ payload: Payload) {
        self.payload = payload
        self.isVisible = true
    }

    func dismiss() {
        isVisible = false
        // Keep payload around briefly so any open animation can finish reading
        // it, then clear so the next meeting starts clean.
        Task { @MainActor [weak self] in
            try? await Task.sleep(for: .milliseconds(400))
            self?.payload = nil
        }
    }

    /// Toggle a task's completed flag from the popup. Persists immediately
    /// via SwiftData. The Library detail view will reflect the change since
    /// it observes the same model.
    func toggleTask(_ id: UUID, in container: ModelContainer) {
        guard var p = payload else { return }
        let ctx = ModelContext(container)
        var desc = FetchDescriptor<TaskItem>()
        desc.fetchLimit = 1000
        let all = (try? ctx.fetch(desc)) ?? []
        guard let task = all.first(where: { $0.id == id }) else { return }
        task.completed.toggle()
        try? ctx.save()

        // Update in-memory payload so UI reflects.
        if let idx = p.actionItems.firstIndex(where: { $0.id == id }) {
            p.actionItems[idx].completed.toggle()
            self.payload = p
        }
    }
}
